'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Plant23HeaderControl

    '''<summary>
    '''pnlPlant23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPlant23 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''hplkBEC_Setup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hplkBEC_Setup As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hplkBEC_Ship_Destination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hplkBEC_Ship_Destination As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hplkBEC_Data_Loader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hplkBEC_Data_Loader As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hplkBEC_Part_Line_Restriction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hplkBEC_Part_Line_Restriction As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hpkBEC_Production_Run control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hpkBEC_Production_Run As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hplkSerialNumber_Search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hplkSerialNumber_Search As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hplkBEC_Part_Line_Restriction_Deleter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hplkBEC_Part_Line_Restriction_Deleter As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hplkBEC_Data_Deleter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hplkBEC_Data_Deleter As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hplkBEC_UpdateProductionRun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hplkBEC_UpdateProductionRun As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hplkBEC_SerialNumbers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hplkBEC_SerialNumbers As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hplkBEC_Generic_SerialNumbers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hplkBEC_Generic_SerialNumbers As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hplkBEC_DelphiGMCrossReference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hplkBEC_DelphiGMCrossReference As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hplk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hplk As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hplkHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hplkHelp As Global.System.Web.UI.WebControls.HyperLink
End Class
