'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
'
Namespace localhost
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BECDATALOOKUPSoap", [Namespace]:="http://tempuri.org/BecWebService/BecWebService")>  _
    Public Class BECDATALOOKUP
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/mfg/BECDATALOOKUP/P23BECDATALOOKUP/BECDATALOOKUP/Becdatalookup.a"& _ 
"smx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BecWebService/BecWebService/GetDate", RequestNamespace:="http://tempuri.org/BecWebService/BecWebService", ResponseNamespace:="http://tempuri.org/BecWebService/BecWebService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetDate() As Date
            Dim results() As Object = Me.Invoke("GetDate", New Object(-1) {})
            Return CType(results(0),Date)
        End Function
        
        '<remarks/>
        Public Function BeginGetDate(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetDate", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetDate(ByVal asyncResult As System.IAsyncResult) As Date
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Date)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BecWebService/BecWebService/RetrieveReleaseInformation", RequestNamespace:="http://tempuri.org/BecWebService/BecWebService", ResponseNamespace:="http://tempuri.org/BecWebService/BecWebService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RetrieveReleaseInformation(ByVal machineName As String, ByVal mesPartID As Long) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("RetrieveReleaseInformation", New Object() {machineName, mesPartID})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginRetrieveReleaseInformation(ByVal machineName As String, ByVal mesPartID As Long, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("RetrieveReleaseInformation", New Object() {machineName, mesPartID}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndRetrieveReleaseInformation(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BecWebService/BecWebService/GetCurrentLotNbr", RequestNamespace:="http://tempuri.org/BecWebService/BecWebService", ResponseNamespace:="http://tempuri.org/BecWebService/BecWebService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetCurrentLotNbr(ByVal psMachineName As String) As String
            Dim results() As Object = Me.Invoke("GetCurrentLotNbr", New Object() {psMachineName})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetCurrentLotNbr(ByVal psMachineName As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetCurrentLotNbr", New Object() {psMachineName}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetCurrentLotNbr(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BecWebService/BecWebService/GetMTMSLocation", RequestNamespace:="http://tempuri.org/BecWebService/BecWebService", ResponseNamespace:="http://tempuri.org/BecWebService/BecWebService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetMTMSLocation(ByVal psPartNbr As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetMTMSLocation", New Object() {psPartNbr})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginGetMTMSLocation(ByVal psPartNbr As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetMTMSLocation", New Object() {psPartNbr}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetMTMSLocation(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BecWebService/BecWebService/GetStandardPackDetailsSat", RequestNamespace:="http://tempuri.org/BecWebService/BecWebService", ResponseNamespace:="http://tempuri.org/BecWebService/BecWebService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetStandardPackDetailsSat(ByVal broadCastCode As String, ByVal ECL As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetStandardPackDetailsSat", New Object() {broadCastCode, ECL})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginGetStandardPackDetailsSat(ByVal broadCastCode As String, ByVal ECL As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetStandardPackDetailsSat", New Object() {broadCastCode, ECL}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetStandardPackDetailsSat(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BecWebService/BecWebService/GetStandardPackDetailsMold", RequestNamespace:="http://tempuri.org/BecWebService/BecWebService", ResponseNamespace:="http://tempuri.org/BecWebService/BecWebService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetStandardPackDetailsMold(ByVal broadCastCode As String, ByVal ECL As String, ByVal systemFlag As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetStandardPackDetailsMold", New Object() {broadCastCode, ECL, systemFlag})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginGetStandardPackDetailsMold(ByVal broadCastCode As String, ByVal ECL As String, ByVal systemFlag As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetStandardPackDetailsMold", New Object() {broadCastCode, ECL, systemFlag}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetStandardPackDetailsMold(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BecWebService/BecWebService/ProcessBroadcastCode", RequestNamespace:="http://tempuri.org/BecWebService/BecWebService", ResponseNamespace:="http://tempuri.org/BecWebService/BecWebService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ProcessBroadcastCode(ByVal broadCastCode As String, ByVal Dept As String, ByRef Result As String, ByVal ContainerType As String, ByVal LabelType As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ProcessBroadcastCode", New Object() {broadCastCode, Dept, Result, ContainerType, LabelType})
            Result = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginProcessBroadcastCode(ByVal broadCastCode As String, ByVal Dept As String, ByVal Result As String, ByVal ContainerType As String, ByVal LabelType As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ProcessBroadcastCode", New Object() {broadCastCode, Dept, Result, ContainerType, LabelType}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndProcessBroadcastCode(ByVal asyncResult As System.IAsyncResult, ByRef Result As String) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Result = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
    End Class
End Namespace
